version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      SENDGRID_API_KEY: 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
      ADMIN_EMAIL: vuongbaolong48@gmail.com
      WEBSITE: http://localhost:1337
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data